timeout: 0
quiet: yes
serial: yes

/KOS v0.1
protocol: limine
path: boot():/boot/kos.elf
kaslr: no
paging_mode: 4level
resolution: 1024x768x32
module_path: boot():/boot/initramfs.cpio
module_string: kos-initramfs
